### ISSUE TITLE
TOTAL CHECKLIST

### ISSUE THREAD

**Issue by thegbars** [scrazyderyl/CS1566-Project-2-3#6]
From Rubric:

- [ ] Any size maze
- [ ] Random maze
- [ ] Floating platform generated
- [ ] Size of the floating platform should match to maze
- [ ] Initial View showing whole island
- [ ] Back to initial view (with animation)
- [ ] Zoom in / out with frustum
- [ ] Trackball Rotation (Project 1)
- [ ] Move to entrance of maze (with animation)
- [ ] Maze movement
- [ ] Collision
- [ ] Maze solver from entrance or current position to exit
- [ ] Moving sun
- [ ] Sun changes color intensity
- [ ] Ambient Light (+ toggle)
- [ ] Diffuse Light (+ toggle)
- [ ] Specular Light (+ toggle)
- [ ] Flashlight
- [ ] Flashlight movement with mouse
